title: workspace
description: Extendible workspace configurator for Laravel
remote_theme: just-the-docs/just-the-docs

url: https://media-code.github.io/workspace

aux_links: # remove if you don't want this link to appear on your pages
  Github: https://github.com/media-code/workspace

callouts:
  note:
    title: note
    color: purple
  warning:
    title: warning
    color: red
